# Generated by Django 4.0.6 on 2023-11-23 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slowo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slowo', models.CharField(max_length=50, unique=True)),
                ('jest_negatywne', models.BooleanField(default=False)),
                ('jest_pozytywne', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sentimentapp.customuser')),
                ('specyficzne_dla_lekarza_pole', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('sentimentapp.customuser',),
        ),
        migrations.CreateModel(
            name='Inzynier',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sentimentapp.customuser')),
                ('specyficzne_dla_inzyniera_pole', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('sentimentapp.customuser',),
        ),
        migrations.CreateModel(
            name='Sentyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('inzynier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentyment', to='sentimentapp.inzynier')),
            ],
        ),
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('punkty', models.IntegerField()),
                ('inzynier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinie_inzyniera', to='sentimentapp.inzynier')),
                ('lekarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinie_lekarza', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
