# Generated by Django 4.2.1 on 2023-11-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slowo',
            name='jest_negatywne',
        ),
        migrations.AlterField(
            model_name='opinia',
            name='punkty',
            field=models.IntegerField(default=0),
        ),
    ]
